ota_password: "OVER-THE-AIR_FIRMWARE_FLASH_PASSWORD"

# API key must be a 32-byte base64-encoded string. A convenient
# generator can be found at https://esphome.io/components/api/#configuration-variables
api_key: "32-BYTE_BASE64_PRE-SHARED-KEY_FOR_API_ENCRYPTION"

wifi_ssid: "SSID_NAME1"
wifi_password: "SSID_PSK1"
